# Generated by Django 2.2.2 on 2019-12-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191215_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='umuryango',
            name='achieved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='umuryango',
            name='pending',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
