# Generated by Django 2.2.2 on 2019-12-17 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191217_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umuryango',
            name='kpi',
        ),
    ]
