# Generated by Django 2.2.2 on 2019-12-17 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_umuryango_kpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='umuryango',
            name='kpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.KPI'),
        ),
    ]
