# Generated by Django 2.2.2 on 2019-12-20 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20191217_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpi',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='kpi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bbbbbb', to='dashboard.KPI'),
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.KPI'),
        ),
        migrations.AlterUniqueTogether(
            name='umuryango',
            unique_together={('kpi', 'sector')},
        ),
    ]
