# Generated by Django 2.2.2 on 2019-12-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20191221_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umuryango',
            old_name='kpi',
            new_name='kpiname',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='status',
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='umuryango',
            unique_together=set(),
        ),
    ]
