# Generated by Django 2.2.2 on 2019-12-20 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20191221_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umuryango',
            old_name='kpiname',
            new_name='kpi',
        ),
    ]
