# Generated by Django 2.2.2 on 2019-12-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20191221_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umuryango',
            old_name='kpi',
            new_name='umuryangokpi',
        ),
    ]
