# Generated by Django 2.2.2 on 2019-12-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20191221_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umuryango',
            old_name='umuryangokpi',
            new_name='kpi',
        ),
        migrations.AddField(
            model_name='umuryango',
            name='kpi1',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dashboard.KPI'),
        ),
    ]
