# Generated by Django 2.2.2 on 2019-12-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20191221_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umuryango',
            name='kpi1',
        ),
        migrations.AddField(
            model_name='umuryango',
            name='achieved',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='umuryango',
            name='target',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
