# Generated by Django 2.2.2 on 2019-12-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20191221_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umuryango',
            name='status',
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='achieved',
            field=models.PositiveIntegerField(default=0, max_length=1),
        ),
    ]
