# Generated by Django 2.2.2 on 2019-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20191221_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umuryango',
            name='target',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
