# Generated by Django 2.2.2 on 2019-12-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20191221_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umuryango',
            name='achieved',
        ),
        migrations.RemoveField(
            model_name='umuryango',
            name='target',
        ),
        migrations.AddField(
            model_name='umuryango',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
