# Generated by Django 2.2.2 on 2019-12-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_umuryang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umuryango',
            name='achieved',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1),
        ),
    ]
