# Generated by Django 2.2.2 on 2019-12-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20191222_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umuryang',
            name='kpi',
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='achieved',
            field=models.PositiveSmallIntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
        migrations.AlterField(
            model_name='umuryango',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (1, 1)], default=1),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.DeleteModel(
            name='Umuryang',
        ),
    ]
