# Generated by Django 2.2.2 on 2019-12-14 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insemination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insemination', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Insemination',
                'verbose_name_plural': 'Insemination',
            },
        ),
        migrations.CreateModel(
            name='InkaZizakurikiranwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inka_zizakurikiranwa', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Inka Zizakurikiranwa',
                'verbose_name_plural': 'Inka Zizakurikiranwa',
            },
        ),
        migrations.CreateModel(
            name='Girinka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girinka', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Girinka',
                'verbose_name_plural': 'Girinka',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
                'unique_together': {('vaccination_name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='UnusedTerassis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Unused Terrasis',
                'verbose_name_plural': 'Unused Terrassis',
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Umuhigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umuhigo', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Umuhigo',
                'verbose_name_plural': 'Umuhigo',
                'unique_together': {('umuhigo', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Ubwanikiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubwanikiro', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Ubwanikiro',
                'verbose_name_plural': 'Ubwanikiro',
                'unique_together': {('ubwanikiro', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Trainings',
                'verbose_name_plural': 'Trainings',
                'unique_together': {('training_name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Seeds',
                'verbose_name_plural': 'Seeds',
                'unique_together': {('seed_name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Pumps_in_Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pumps', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Pumps in Sector',
                'verbose_name_plural': 'Pumps in Sectors',
                'unique_together': {('number_of_pumps', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Ha_irrigated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_irrigated', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Ha Irrigated',
                'verbose_name_plural': 'Ha Irrigated',
                'unique_together': {('ha_irrigated', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Fertilizers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Fertilizers',
                'verbose_name_plural': 'Fertilizers',
                'unique_together': {('name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='FertilizerImprovedSeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Fertilizer and  Improved Seeds',
                'verbose_name_plural': 'Fertilizer and Improved Seeds',
                'unique_together': {('target', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=50)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Crops',
                'verbose_name_plural': 'Crops',
                'unique_together': {('crop_name', 'sector')},
            },
        ),
        migrations.CreateModel(
            name='Banana_and_Rehabilitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('target', models.PositiveIntegerField()),
                ('achieved', models.PositiveIntegerField(default=0)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Sector')),
            ],
            options={
                'verbose_name': 'Banana and Rehabilitation',
                'verbose_name_plural': 'Banana and Rehabilitation',
                'unique_together': {('name', 'sector')},
            },
        ),
    ]
